= Основные понятия

== Функция

Функцией в программировании называется законченный участок программы, решающий определённую задачу --
обычно это часть большой задачи, которую решает программа в целом,
хотя в простых случаях написание программы сводится к написанию одной функции.
Как и у функции в математическом смысле, у функции в программировании есть входы (параметры), выход (результат)
и определение, указывающее, как рассчитывается значение выхода по заданным значениям входов.

Определение простых функций на Котлине мало отличается от определения математических функций.
Рассмотрим для примера математическую функцию f(x) = x^2^. На Котлине она будет записана так:

[source,kotlin]
----
fun f(x: Int) = x * x
// или
fun f(x: Double) = x * x
----

В этом определении **fun** является __ключевым словом__, с которого начинается определение любой функции в Котлине.
**f** -- это __имя__ функции, **x** -- __параметр__ функции, **= x * x** -- __тело__ функции.
Поскольку операция вычисления квадрата числа в Котлине отсутствует, результат вычисляется как произведение **x * x**.

Нотация **: Int** или **: Double** задаёт так называемый __тип__ параметра **x** и требует пояснения.
__Тип__ в программировании подобен области допустимых значений в математике;
математически, запись **x: Int** близка к записи x &isin; Z, а **x: Double** соответственно x &isin; R.