= 12. Разработка классов-контейнеров

В этом разделе мы поговорим о проектировании классов другого вида, а именно классов-контейнеров. Так мы называем классы, содержащие внутри себя наборы однотипных данных. Список, множество, таблица, телефонная или адресная книга, матрица -- всё это примеры классов-контейнеров. 

В качестве примера рассмотрим проектирование класса "однонаправленный связный список". Связный список имеет организацию, подобную цепи -- он состоит из узлов, которые "сцепляются" друг с другом путём сохранения ссылки на соседний или соседние узлы. В частности, в __однонаправленном__ связном списке каждый узел хранит в себе ссылку на следующий узел. При этом последний узел вместо ссылки на следующий хранит `null`, а ссылка на первый узел сохраняется в классе отдельно. Более подробное описание с иллюстрациями имеется в статье Википедии "Связный список".

Для упрощения задачи будем считать, что наш список `SinglyLinkedList` умеет хранить исключительно целые числа; в качестве одного из упражнений вы можете попробовать изменить данный класс так, чтобы он мог хранить данные настраиваемого типа (подробнее про настраиваемые типы см. раздел 9). Опишем для начала один узел цепи в виде вложенного класса.

[source,kotlin]
----
class SinglyLinkedList {
    // ...
    private class Node(
        val value: Int,
        var next: Node? // next == null означает, что данный узел -- последний в списке
    )
    // ...
}    
----

Узел хранит в себе значение `value` и ссылку на следующий узел `next`. 

Напомним, что создание класса не приводит само по себе к созданию каких-либо данных или переменных -- для этого необходимо создать объекты этого класса. 



== Упражнения

Откройте каталог `src/lesson12/task1` в проекте. Внутри находится файл с рассмотренным выше примером `SinglyLinkedList.kt`, а также четыре других файла с различными заданиями на проектирование классов-контейнеров. Задания имеют близкую сложность; самым сложным из них является `OpenHashSet.kt`, и это единственное из заданий, предполагающее создание настраиваемого (generic) класса. Суть каждого задания описана в заголовочном комментарии класса, плюс дан короткий комментарий к каждой функции класса.

Выберите одно из заданий, которое кажется вам посильным. Замените на реализацию все `TODO()`, которые есть в классе. После этого откройте тесты для данного класса из каталога `test/lesson12/task1`. Подумайте над тем, какие из важных случаев рассмотрены тестами, а какие -- нет. Дополните тесты нерассмотренными случаями. После этого запустите тесты для вашего класса и добейтесь их полного прохождения.

Поздравляем вас с прохождением всех разделов нашего курса! 

