= 8. Файловые операции

Программы, которые мы пишем, так или иначе должны взаимодействовать с пользователем и внешней средой --
операционной системой, устройствами компьютера, сетью Интернет.
Простейшим способом взаимодействия является ввод с консоли и вывод на консоль,
но сейчас такой способ применяется крайне редко.
Более совершенным способом взаимодействия являются __файлы__ --
многие программы берут из них настроечную или входную информаци,
и используют их для сохранения результатов своей работы или различных настроек.
Например, всевозможные __редакторы__ позволяют открывать файлы в определённом формате,
просматривать и/или изменять их, сохранять файлы на диске компьютера или в сети Интернет.

В библиотеке Java внутри пакета `java.io` имеется ряд классов, обеспечивающих возможность работы с файлами,
а библиотека Котлина дополняет эти классы некоторыми удобными возможностями.
Как обычно, рассмотрим часть этих возможностей на примере.

[source,kotlin]
----
/**
 * Пример
 *
 * Во входном файле с именем inputName содержится некоторый текст.
 * Вывести его в выходной файл с именем outputName, выровняв по левому краю,
 * чтобы длина каждой строки не превосходила lineLength.
 * Слова в слишком длинных строках следует переносить на следующую строку.
 * Слишком короткие строки следует дополнять словами из следующей строки.
 * Пустые строки во входном файле обозначают конец абзаца,
 * их следует сохранить и в выходном файле
 */
fun alignFile(inputName: String, lineLength: Int, outputName: String) {
    val outputStream = File(outputName).bufferedWriter()
    var currentLineLength = 0
    for (line in File(inputName).readLines()) {
        if (line.isEmpty()) {
            outputStream.newLine()
            if (currentLineLength > 0) {
                outputStream.newLine()
                currentLineLength = 0
            }
        }
        for (word in line.split(" ")) {
            if (currentLineLength > 0) {
                if (word.length + currentLineLength >= lineLength) {
                    outputStream.newLine()
                    currentLineLength = 0
                }
                else {
                    outputStream.write(" ")
                    currentLineLength++
                }
            }
            outputStream.write(word)
            currentLineLength += word.length
        }
    }
    outputStream.close()
}
----