= Введение

Языки программирования -- интереснейшая область современной техники.
За последние 30-40 лет информационные технологии разрослись до невероятных пределов,
и сейчас мало кто в состоянии обозреть эту область в полном объёме.
Компьютерные программы выросли с нескольких сотен строк до десятков миллионов строк,
применяются сейчас в самых разных областях и запускаются на самых разных __платформах__, например:

 * обыкновенные программы для персонального компьютера, часто называемые desktop-программами;
 * web-программы, которые делятся, в свою очередь, на __клиентскую__ часть, выполняющуюся на компьютере пользователя, и __серверную__, выполняющуюся на сервере;
 * __мобильные__ программы для планшетов, смартфонов и других мобильных устройств;
 * __системные__ программы, являющиеся частью операционной системы;
 * __встраиваемые__ программы, являющиеся частью встраиваемых систем управления (применяемые, например, в транспорте, банкоматах, станках с программным управлением, при программировании роботов).

Для написания разных видов программ сейчас применяются разные языки программирования.
Например, в сфере __мобильных__ программ сейчас правят бал языки Swift (мобильные устройства под управлением iOS)
и Java (устройства под управлением Android).
__Системные__ программы, как правило, пишутся на языках C или {cpp}.
Эти же языки долгое время использовались и для создания __встраиваемых__ программ,
но в последние годы в этой области набирает популярность язык Java.
Для написания web-клиентов часто используется JavaScript, а в простых случаях -- язык разметки страниц HTML.
Web-серверы используют опять-таки Java (в сложных случаях), а также Python и PHP (в более простых).
Наконец, простые desktop-программы сейчас могут быть написаны на самых разных языках,
и выбор во многом зависит от сложности программы, области её использования, предполагаемой операционной системы.
В первую очередь следует назвать языки Java, {cpp}, C#, Python, Visual Basic, Ruby, Swift.

Самым универсальным и одновременно самым распространённым языком программирования
на данный момент следует считать язык Java.
Java в широком смысле -- не только язык, но и платформа для выполнения программ
под самыми разными операционными системами и на разной аппаратуре.
Такая универсальность обеспечивается наличием виртуальной машины Java --
системной программы, интерпретирующей Java байт-код в машинные коды конкретного компьютера или системы.
Java также включает богатейший набор библиотек для разработки.

Однако, для начинающих язык Java является несколько многословным и сложным.
Это пособие посвящено другому языку программирования, спутнику Java -- языку Котлин.
Котлин -- молодой, лёгкий для изучения язык программирования, позволяющий писать программы под платформы JVM и Android
более лаконично, просто и с меньшим количеством ошибок по сравнению с языком Java.
Котлин и Java -- полностью __интероперабельные__ языки,
поэтому одна и та же программа может быть частично написана на Котлине, частично на Java.
Программы на Котлине могут использовать все имеющиеся Java-библиотеки, и наоборот.
На данный момент программы на Котлине пишут десятки тысяч программистов,
основная ниша его промышленного применения -- мобильные программы под платформу Android
и в несколько меньшей степени -- web-разработка.

В ходе изучения Котлина мы изучим также многие элементы стандартной библиотеки Java,
а понимание работы программ на Котлине во многом упростит понимание работы Java-программ.

== Что требуется для начала

Самый простой способ начать программировать на Котлине -- зайти на сайт http://try.kotlinlang.org.
Имеющаяся там "песочница" позволяет писать программы прямо в браузере,
с возможностью выполнять и сохранять свои программы и проходить обучающие курсы.

Масштабы песочницы, однако, достаточны только для небольших программ,
а более-менее серьёзные программы, как правило, разрабатываются в интегрированной среде (IDE).
Разработка под платформу Java в любом случае требует установки пакета JDK,
который необходимо скачать с сайта компании Oracle: http://www.oracle.com/technetwork/java/javase/downloads/index.html.
Первое время вам потребуется Java Platform, Standard Edition,
на август 2016 года последняя её версия -- Java SE 8.102.

В качестве интегрированной среды разработки рекомендую установить Intellij IDEA Community Edition,
её следует брать отсюда: https://www.jetbrains.com/idea/#chooseYourEdition.
Community Edition является полностью бесплатной,
базовая версия обеспечивает поддержку программирования на Java, Kotlin, Scala, Groovy,
поддержку систем контроля версий Git, Mercurial, SVN, интеграцию с системами сборки Maven и Gradle.

Для интеграции IDEA с системой контроля версий Git необходимо установить один из клиентов Git.
Таких клиентов существует много; "родной" Git клиент можно скачать отсюда: https://git-scm.com/downloads.
Имейте в виду, что в IDEA интегрирован собственный Git-плагин, уже имеющий графический интерфейс,
поэтому скачивать и устанавливать клиенты Git с графическим интерфейсом (GUI Clients) необязательно.

== Учебный проект

В ходе обучения мы будем активно использовать проект "Котлин как первый язык программирования", содержащий текст данного пособия и около сотни различных задач на языке Kotlin.
Оригинальный код данного проекта доступен по адресу https://github.com/Kotlin-Polytech/KotlinAsFirst2016 на сайте GitHub, который является специализированным хранилищем программных кодов и основан на системе контроля версий Git.
Для того, чтобы начать работать с этим проектом, Вам необходимо выполнить следующие действия.

1. Зарегистрироваться на https://github.com/ (в случае, если у Вас еще нет GitHub аккаунта). Далее выбранное Вами имя будет обозначаться как <USERNAME>.
1. Создать специальную копию репозитория проекта -- _форк_. Для этого достаточно зайти на страницу проекта https://github.com/Kotlin-Polytech/KotlinAsFirst2016 и нажать кнопку `Fork` в правом верхнем углу страницы. После этого Ваша персональная копия проекта станет доступна по адресу https://github.com/<USERNAME>/KotlinAsFirst2016, и всю работу по решению различных задач Вы должны выполнять именно с Вашей копией.
1. Для загрузки проекта в Intellij IDEA следует выполнить команду `Check out from Version Control` -> `GitHub` из окна `Welcome to Intellij IDEA` (или `File` -> `New` -> `Project from Version Control` -> `GitHub` из окна проекта), в появившемся окне ввести Git Repository URL https://github.com/<USERNAME>/KotlinAsFirst2016 и место на компьютере, куда будет скачан проект (Parent Directory).
1. При открытии проекта в правом нижнем углу среды разработки Вы увидите сообщение "Non-managed pom.xml file found" с предложениями `Add as Maven project` и `Disable notification`. Нажмите на ссылку `Add as Maven project`, это необходимо для загрузки на Ваш компьютер всех библиотек, необходимых для работы обучающего проекта.

Проект содержит задачи, разбитые на восемь уроков (lesson).
Тексты задач доступны через окно Project в Intellij IDEA (открывается комбинацией клавиш Alt+1).
В папках src/lessonX, где X -- номер урока, находятся примеры решённых задач к данному уроку,
тексты задач, которые необходимо решить и готовые заглушки функций для написания решения.
В папках test/lessonX находятся тестовые функции к задачам. Подробнее о задачах и тестах см. раздел 1 этого пособия.

При открытии в первый раз любого файла с расширением kt Вы увидите сообщение над ним `Project SDK is not defined` и ссылку `Setup SDK` справа. Нажмите на эту ссылку и выберете JDK 1.8 для работы с проектом в появившемся окне. Если список JDK в окне пуст, или не содержит JDK 1.8, следует нажать на клавишу `Configure`, затем зелёный плюс в верхнем левом углу и зарегистрировать установленную на Вашем компьютере JDK 1.8 в Intellij IDEA. Если Вы забыли установить JDK, это следует сделать, предварительно скачав её с сайта Oracle.

Работа с проектом будет осуществляться в рамках системы контроля версий Git,
а Ваши решения будут представлять собой коммиты в соответствующий репозиторий.
Коммит -- это законченное изменение текста проекта (например, решение одной или нескольких задач из какого-либо урока).
Для более глубокого понимания того, что такое системы контроля версий, зачем они нужны и как с ними работать,
рекомендуется пройти один или несколько обучающих уроков из Интернета.
Несколько примеров подобных туториалов приведены ниже:

* https://githowto.com/ru/
* https://try.github.io/levels/1/challenges/1
* https://guides.github.com/activities/hello-world/

В ходе освоения различных уроков вы можете обращаться за помощью к преподавателю или своим однокурсникам,
но важно, чтобы ХОТЯ БЫ ОДНА задача из каждого урока была решена вами самостоятельно.
Имейте в виду, что задачи разбиты на пять уровней сложности, сложность задачи указана в комментарии к ней
(тривиальная Trivial, простая Easy, средняя Normal, сложная Hard и очень сложная Impossible).
Решайте в первую очередь те задачи, которые кажутся вам по силам, но иногда пытайтесь решать и более сложные.
Если у вас нет идей, как решить какую-либо сложную задачу -- попросите преподавателя о подсказке.
Оценка по итогам курса будет зависеть от сложности решённых вами задач из различных уроков.

Законченное решение задачи (или нескольких задач из одного урока) следует
фиксировать в виде коммита в системе контроля версий. Для этого необходимо:

1. Зайти в окно Version Control среды Intellij IDEA. Это делается из меню `View` -> `Tool Windows` либо с помощью комбинации клавиш `Alt+9`.
1. В нём щелчком мыши выбрать вкладку `Local Changes` (локальные изменения). Убедитесь, что файлы, которые вы меняли, присутствуют в этом окне.
1. В контекстном меню выберете команду `Commit Changes`. В появившемся окне введите осмысленный комментарий к вашему изменению (например, "Решена задача такая-то"), откройте выпадающее меню справа от кнопки `Commit` и в нём выберете команду `Commit and Push`.
1. При появлении соответствующих окон введите своё имя и e-mail для идентификации автора коммита (эти поля заполняются один раз), а также логин и пароль для Вашего аккаунта на GitHub.

После этого Вы должны отправить эти задачи на проверку в основной репозиторий
в виде _запроса на обновление_ (pull request). Для этого необходимо сделать следующее.

1. Зайти на https://github.com/<USERNAME>/KotlinAsFirst2016/pulls и нажать кнопку `New pull request`.
1. Проверить, что следующие поля содержат правильные значения:
* `base fork` -> `Kotlin-Polytech/KotlinAsFirst2016`
* `base` -> `master`
* `head fork` -> `<USERNAME>/KotlinAsFirst2016`
* `compare` -> `master`
1. Проверить, что Ваши изменения могут быть применены к основному репозиторию -- об этом свидетельствует зеленая надпись **Able to merge** (и в нормальной ситуации Вы её должны увидеть). Если данная надпись не появляется и вместо неё вы видите надпись **Can't automatically merge**, всё равно создайте запрос (см. следующий пункт), но после этого отправьте сообщение на электронную почту своему преподавателю.
1. Нажать кнопку `Create pull request` и заполнить его имя и краткое описание. Желательно использовать говорящие имена и адекватные описания содержания выполненной Вами работы.

Созданный запрос будет автоматически проверен (это возможно, только если вы видели надпись **Able to merge** при создании запроса), после чего на его странице появится краткий отчет, в котором будет указано:

* Задачи из каких уроков решались в данном пулл реквесте
* Сколько задач каждого типа было успешно решено
* Список успешно решенных задач
* Список задач, решенных не полностью или неправильно, с перечислением некоторых из неудавшихся тестов.

Преподаватели могут написать в Pull Request дополнительный комментарий, описывающий сделанные вами ошибки.
Если же все решённые вами задачи успешно прошли тестирование, Pull Request будет закрыт --
это свидетельствует о том, что ваши решения приняты в полном объёме.

В том случае, если все задачи, которые Вы хотели решить, успешно проверены, Вы можете приступать к следующим задачам.
Если часть задач решена неправильно, постарайтесь исправить возможные ошибки при помощи предоставленных Вам тестов.
В случае, если Вы уверены в правильности решения или не можете понять, где Вы ошиблись при решении, можете обратиться к преподавателю.
