= 4.5. Хранение данных в памяти компьютера

В этом разделе мы поговорим о том, как различные элементы программы сохраняются в памяти PC.
Поскольку данное пособие посвящено Котлину как JVM-языку, они сохраняются в памяти JVM как виртуального компьютера.
Тем не менее, организация памяти JVM имеет немало общего с организацией памяти настоящего компьютера.
Поговорим об этом подробнее.

== Биты, байты и килобайты

Единицей измерения информации (например, хранящейся в памяти или на диске) является __бит__ --
элементарная ячейка, имеющая всего два состояния (0 и 1, либо **true** и **false**).
Биты объединяеются в __байты__ -- в одном байте 2^3^ = 8 бит.
Байты, в свою очередь, объединяются в __килобайты__ (Кб) -- в одном килобайте 2^10^ = 1024 байт.
Обратите внимание -- не 1000 байт, а именно 1024 байт,
поскольку компьютеру удобнее, чтобы данные размерности были степенями двойки.
В свою очередь, в одном мегабайте (Мб) 1024 Кб, в одном гигабайте (Гб) 1024 Мб, в одном терабайте (Тб) 1024 Гб.

== Целые числа

Целые числа типа **Int** занимают в памяти четыре байта, или 32 бита,
при хранении используется двоичная система счисления.
Модуль числа занимает 31 бит из 32,
старший бит занимает знак (он равен 0 для положительных и -1 для отрицательных чисел).
Модуль положительных чисел хранится обычным образом, а отрицательных -- в так называемом __дополнительном коде__.
При этом вместо модуля числа `|x|` в памяти хранится значение `2^31^ - |x|`,
например, `2^31^ - 1` для числа `-1` или `0` для числа `-2^31^`.
Использование дополнительного кода позволяет упростить операции сложения и вычитания чисел для компьютера.

Помимо типа **Int**, в Котлине имеется ещё три целочисленных типа, а именно:

 * **Byte** -- целое число от -128 до 127, занимает один байт;
 * **Short** -- целое число от -32768 до 32767, занимает два байта;
 * **Long** -- целое число от `-2^63^` до `2^63^ - 1`, занимает восемь байт.

Подобные целые числа устроены по тому же принципу, что и числа типа **Int**.
Следует иметь в виду, что при работе с типом **Long** нельзя использовать литералы типа **Int**:

[source,kotlin]
----
val long1: Long = 42  // Error!
val long2: Long = 42L // OK!
----

Вместо них используются литералы типа **Long** с суффиксом `L`.

Как правило, в программах используется именно тип **Int** для хранения целых чисел.
Исключения составляют следующие случаи:

 * когда диапазон типа **Int** недостаточен для целей программы, следует использовать **Long**;
 * когда требуется сохранить __большое__ (измеряемое, минимум, десятками тысяч) количество чисел с маленьким диапазоном -- следует использовать **Byte** или **Short** для экономии памяти.

== Вещественные числа

== Символы
