= 5. Разбор строк

Распознавание содержимого строки, тем или иным путём полученной от пользователя --
одна из важнейших задач в программировании.
Традиционное название этой задачи -- __разбор__ строки (или текста), либо __парсинг__ (от английского parsing) строки.
Разбираемой строкой может быть как что-то, непосредственно введённое пользователем с клавиатуры,
так и содержимое какого-либо файла, а часто и строчка, пришедшая по сети (например, содержимое HTTP-запроса).
Отметим, что анализ текстов программ также включает разбор текста программы как одну из решаемых задач.

== Разбиение строки на части

Простая задача на эту тему может выглядеть так.
Некоторая строка содержит текущее время в формате "11:34:45", то есть часы, минуты и секунды, разделённые двоеточием.
Написать функцию, которая __разберёт__ эту строку и рассчитает количество секунд, прошедшее с начала дня.
В нашем случае ответ должен быть 11 * 3600 + 34 * 60 + 45 = 41685. Решение на Котлине может выглядеть так:

[source,kotlin]
----
fun timeStrToSeconds(str: String): Int {
    val parts = str.split(":")
    var result = 0
    for (part in parts) {
        val number = part.toInt()
        result = result * 60 + number
    }
    return result
}
----

Данная функция начинается с разбиения строки на части.
Для этой цели мы используем функцию `str.split(":")`, у которой разбиваемая строка является __получателем__,
а аргумент задаёт последовательность символов, по которой происходит разбиение.
Результатом функции **split** является СПИСОК строк, содержащий части исходной строки.
В нашем случае строка содержит два двоеточия, поэтому частей будет три, например, "11", "34" и "45".

Получив части нашей строки -- часы, минуты и секунды -- нам необходимо каждую из них превратить из строки в целое число.
Это преобразование осуществляется оператором `val number = part.toInt()`.
Похожие функции нам уже встречались в уроке 2 -- они использовались для преобразования
целых чисел в вещественные `n.toDouble()` или вещественных в целые `x.toInt()`.
Оказывается, функции `toInt()` и `toDouble()` определены и для получателя типа String.

Мутирующая переменная **result** используется для формирования результата.
В процессе выполнения цикла **for** часы будут умножены на 60 дважды, минуты -- один раз, а секунды оставлены как есть
(проверьте этот факт). В результате мы получим количество секунд, прошедшее с начала дня.

== Исключения

== Отображения

== Регулярные выражения

== Форматные строки

