= Введение

Языки программирования -- интереснейшая область современной техники.
За последние 30-40 лет информационные технологии разрослись до невероятных пределов,
и сейчас мало кто в состоянии обозреть эту область в полном объёме.
Компьютерные программы выросли с нескольких сот строк до десятков миллионов строк,
применяются сейчас в самых разных областях и запускаются на самых разных __платформах__, например:

 * обыкновенные программы для персонального компьютера, часто называемые desktop-программами;
 * web-программы, которые делятся, в свою очередь, на __клиентскую__ часть, выполняющуюся на компьютере пользователя, и __серверную__, выполняющуюся на сервере
 * __мобильные__ программы для планшетов, смартфонов и других мобильных устройств
 * __системные__ программы, являющиеся частью операционной системы
 * __встраиваемые__ программы, являющиеся частью встраиваемых систем управления (применяемые, например, в транспорте, банкоматах, станках с программным управлением, при программировании роботов)

Для написания разных видов программ сейчас применяются разные языки программирования.
Например, в сфере __мобильных__ программ сейчас правят бал языки Swift (мобильные устройства под управлением iOS)
и Java (устройства под управлением Android).
__Системные__ программы, как правило, пишутся на языках C или C++.
Эти же языки долгое время использовались и для создания __встраиваемых__ программ,
но в последние годы в этой области набирает популярность язык Java.
Для написания web-клиентов часто используется JavaScript, а в простых случаях -- язык разметки страниц HTML.
Web-серверы используют опять-таки Java (в сложных случаях), а также Python и PHP (в более простых).
Наконец, простые desktop-программы сейчас могут быть написаны на самых разных языках,
и выбор во многом зависит от сложности программы, области её использования, предполагаемой операционной системы.
В первую очередь следует назвать языки Java, C++, C#, Python, Visual Basic, Ruby, Swift.

Самым универсальным и одновременно самым распространённым языком программирования
на данный момент следует считать язык Java.
Java в широком смысле -- не только язык, но и платформа для выполнения программ
под самыми разными операционными системами и на разной аппаратуре.
Такая универсальность обеспечивается наличием виртуальной машины Java --
системной программы, интерпретирующей Java байт-код в машинные коды конкретного компьютера или системы.
Java также включает богатейший набор библиотек для разработки.

Однако, для начинающих язык Java является несколько многословным и сложным.
Это пособие посвящено другому языку программирования, спутнику Java -- языку Котлин.
Котлин -- молодой, лёгкий для изучения язык программирования, позволяющий писать программы под платформы JVM и Android
более лаконично, просто и с меньшим количеством ошибок по сравнению с языком Java.
Котлин и Java -- полностью __интероперабельные__ языки,
поэтому одна и та же программа может быть частично написана на Котлине, частично на Java.
Программы на Котлине могут использовать все имеющиеся Java-библиотеки, и наоборот.

В ходе изучения Котлина мы изучим также многие элементы стандартной библиотеки Java,
а понимание работы программ на Котлине во многом упростит понимание работы Java-программ.

== Что требуется для начала



