= 12. Разработка классов-контейнеров

Раздел находится в процессе написания (TODO).

== Упражнения

Откройте каталог `src/lesson12/task1` в проекте. Внутри находится файл с рассмотренным выше примером `SinglyLinkedList.kt`, а также четыре других файла с различными заданиями на проектирование классов-контейнеров. Задания имеют близкую сложность; самым сложным из них является `OpenHashSet.kt`, и это единственное из заданий, предполагающее создание настраиваемого (generic) класса. Суть каждого задания описана в заголовочном комментарии класса, плюс дан короткий комментарий к каждой функции класса.

Выберите одно из заданий, которое кажется вам посильным. Замените на реализацию все `TODO()`, которые есть в классе. После этого откройте тесты для данного класса из каталога `test/lesson12/task1`. Подумайте над тем, какие из важных случаев рассмотрены тестами, а какие -- нет. Дополните тесты нерассмотренными случаями. После этого запустите тесты для вашего класса и добейтесь их полного прохождения.

Поздравляем вас с прохождением всех разделов нашего курса! 

