= 6. Простые классы

__Классы__ придуманы программистами в первую очередь для структурирования данных.
Мы с вами уже видели, что в более-менее сложных задачах часто бывает необходимо использование составных типов -- 
таких, как списки или строки;
кстати говоря, и список и строка тоже являются __классами__, но только классами, определёнными в библиотеке языка.

Списки, однако, ограничены использованием элементов одного типа.
Кроме этого, доступ к элементам в них происходит по номеру, что не всегда удобно.
Рассмотрим, например, простую задачу вычисления расстояния между точками `p1` и `p2`:

[source,kotlin]
----
fun distance(x1: Double, y1: Double, x2: Double, y2: Double) = sqrt(sqr(x2 - x1) + sqr(y2 - y1))
----

Сразу же бросается в глаза, что в условии задачи мы говорили о двух точках, 
а в заголовке функции имеем вместо этого четыре параметра, по два для каждой из точек.
Гораздо понятнее было бы иметь функцию в таком виде:

[source,kotlin]
----
fun distance(p1: Point, p2: Point) = ...
----

Можно ли так написать заголовок функции? Да, конечно! 
Но для этого придётся определить в программе тип `Point`.
В Котлине, самый простой способ это сделать выглядит так:

[source,kotlin]
----
class Point(val x: Double, val y: Double)

fun distance(p1: Point, p2: Point) = sqrt(sqr(p2.x - p1.x) + sqr(p2.y - p1.y))
----

Строчка `class Point(...)` определяет новый __класс__.
Такое определение всегда начинается с ключевого слова **class**, за которым следует __имя__ класса. 
Имена классов формируются по обычным правилам; 
не забывайте, что их рекомендуется начинать с прописной буквы -- в отличие от имён переменных и функций.

В круглых скобках перечисляется, какие данные необходимы для создания новой точки.
Создание новой точки -- это функция, но функция специальная -- __конструктор__.
Поэтому и параметры этой функции определяются почти (но не совсем) так же, как и для обычной функции.
В данном случае мы видим, что создания точки необходимо задать её вещественные координаты `x` и `y`.

Внимательный читатель заметит отличие в определении `x` и `y` от обычных параметров функции -- 
оно заключается в добавлении ключевого слова **val** перед именем каждого параметра.
Ключевое слово **val** перед параметром __конструктора__ превращает его из простого параметра в __свойство__ класса.
__Свойства__ в данном случае задают внутреннюю структуру каждой точки.
Свойство, заданное через **val**, можно читать, используя имя переменной (или параметра) типа `Point` и символ точки: `p1.x`.
Вместо **val** можно использовать **var** (мутирующее свойство), тогда свойство можно будет также изменять: `p1.x = ...`.
Обращение к свойству напоминает вызов функции, имеющей получателя, но в нём отсутствуют круглые скобки и набор аргументов.
В этом месте можно вспомнить и понять, что `list.size` является свойством списка (размер), а `str.length` -- свойством строки (длина).

Итак, каждая наша точка имеет два свойства -- `x` и `y`.
Обратите внимание, что, определив класс, мы определили и тип, но не определили ни одной переменной данного типа.
Создаются новые точки следующим простым образом:

[source,kotlin]
----
fun usePoints() {
    // Здесь мы просто перечисляем аргументы
    val a = Point(0.0, 3.0)
    // А здесь перед каждым аргументом мы написали имя параметра, которому он соответствует
    val b = Point(x = 4.0, y = 3.0)
    println(distance(a, b)) // 5.0
}
----
