= Основные понятия

== Функция

Функцией в программировании называется законченный участок программы, решающий определённую задачу --
обычно это часть большой задачи, которую решает программа в целом,
хотя в простых случаях написание программы сводится к написанию одной функции.
Как и у функции в математическом смысле, у функции в программировании есть входы (параметры), выход (результат)
и определение, указывающее, как рассчитывается значение выхода по заданным значениям входов.

Определение простых функций на Котлине мало отличается от определения математических функций.
Рассмотрим для примера математическую функцию f(x) = x^2^. На Котлине она будет записана так:

[source,kotlin]
----
fun f(x: Int) = x * x
// или
fun f(x: Double) = x * x
----

В этом определении **fun** является __ключевым словом__, с которого начинается определение любой функции в Котлине.
**f** -- это __имя__ функции, **x** -- __параметр__ функции, **= x * x** -- __тело__ функции,
определяющее, как следует вычислять её __результат__.
Поскольку операция вычисления квадрата числа в Котлине отсутствует, результат вычисляется как произведение **x * x**.
Строчка, начинающаяся с символов **//**, является так называемым комментарием -- он предназначен
для чтения человеком и никак не влияет на поведение функции или программы.

=== Тип параметров / результата функции

Нотация **: Int** или **: Double** задаёт так называемый __тип__ параметра **x** и требует пояснения.
__Тип__ в программировании подобен области допустимых значений в математике;
математически, запись **x: Int** близка к записи x &isin; Z, а **x: Double** соответственно x &isin; R.
Присутствие в определении функции типов параметров в Котлине **обязательно**;
наличие типов позволяет функции "понять", для каких входов она применима,
а для каких её использование является ошибкой.

Заметим, что __тип__ имеется не только у параметров функции, но и у её результата.
Полная запись функции возведения в квадрат в Котлине (для целого параметра) выглядит следующим образом:

[source,kotlin]
----
fun f(x: Int): Int = x * x
----

Здесь нотация **: Int** перед знаком равенства задаёт тип результата функции.
В Котлине в некоторых случаях **необязательно** записывать тип результата функции явно,
поскольку функция сама может __вывести__ этот тип, зная типы своих параметров.
В данном случае известно, что произведение целого числа на целое также даст целое число,
что позволяет использовать сокращённую форму записи без указания типа результата.

В Котлине определяется некоторое количество стандартных типов;
помимо них, программист имеет право определять свои типы, используя так называемые __классы__ (о них речь пойдёт позже).
На первых порах нам потребуются следующие стандартные типы:

 * Int -- целое число в диапазоне от -2^31^ до 2^31^-1
 * Double -- вещественное число в диапазоне (примерно) от -1.7 * 10^308^ до 1.7 * 10^308^, имеющее точность в (примерно) 15 десятичных цифр
 * Boolean -- так называемый __логический__ или __булевский__ тип с ровно двумя возможными значениями -- **true** и **false**
 * Char -- символ (одиночный), например **Z** или **Я**; значением может являться любой символ, присутствующий в таблице "Unicode", с кодом от 0 до 2^16^-1
 * String -- строка, состоящая из любого количества (в том числе из нуля) одиночных символов

=== Имена

В приведённых примерах **f** являлось именем функции, а **x** -- именем её параметра.
По правилам языка Котлин, любое __имя__ обязано начинаться с буквы или символа **&lowbar;** и
может состоять из букв, цифр и символа **&lowbar;**.
Следует помнить, что Котлин **различает** строчные и прописные буквы;
рекомендуется всегда начинать имена параметров и функций со строчной буквы, а имена типов -- с прописной буквы.
Имя, состоящее из нескольких слов, обычно записывается в так называемой camel case нотации, например **bigNumber**.
Не рекомендуется:

 * использование букв не из латинского алфавита, например **имя**;
 * использование символа **&lowbar;** и цифр в именах, например **flag&lowbar;123**;
 * использование транслитерации в именах, например **dlina**.