= 6.5. Графы

Граф -- это математическая абстракция, имеющая, тем не менее, очень широкое применение в программировании.
Граф состоит из множества так называемых __вершин__, которые обычно изображаются как точки на плоскости,
и __рёбер__ (другое название ребра -- __дуга__), которые эти вершины соединяют.
Пример графа приведён на рисунке (TODO).

Чаще всего графы применяются для описания различных схем, например, 
соединения узлов в компьютерной сети или городов и других пунктов на карте местности.
Типичная решаемая с помощью графа задача -- поиск кратчайшего маршрута из одного пункта в другой.
Довольно часто граф, помимо информации о своих вершин и рёбрах, содержит вспомогательную информацию.
Например, для схемы дорог ей могут быть названия городов, соответствующих вершинам графа,
или длины дорог, соответствующих рёбрам графа. Пример (TODO):

Структуры данных, __подобные__ графам, могут возникать в различных задач поиска оптимального решения.
Например, в `lesson6/task2` имеется задача о поиске наиболее короткой траектории движения шахматного коня.
Эту задачу можно описать с помощью графа, вершинами которого являются клетки шахматной доски,
а рёбра соединяют те из них, между которыми может двигаться шахматный конь.
Для фрагмента шахматной доски граф может выглядеть примерно так (TODO):

Описать граф на языке программирования можно разными способами.
В той же задаче о маршруте шахматного коня лучше вообще не хранить информацию о вершинах графа,
достаточно лишь уметь по конкретной клетке найти связанные с ней ребром --
то есть, те клетки, в которые из данной клетки может прыгнуть конь.
В других задачах, тем не менее, информацию о вершинах и рёбрах графа есть смысл сохранить,
и тогда следует для этой цели использовать собственный __класс__.
Пример реализации такого класса приведён ниже.

[source,kotlin]
----
class Graph {
    private data class Vertex(val name: String) {
        val neighbors = mutableSetOf<Vertex>()
    }

    private val vertices = mutableMapOf<String, Vertex>()

    private operator fun get(name: String) = vertices[name] ?: throw IllegalArgumentException()

    fun addVertex(name: String) {
        vertices[name] = Vertex(name)
    }

    private fun connect(first: Vertex, second: Vertex) {
        first.neighbors.add(second)
        second.neighbors.add(first)
    }

    fun connect(first: String, second: String) = connect(this[first], this[second])
}
----

Описанный здесь `Graph` является довольно сложным классом.
Он включает в себя функцию `addVertex` (добавить вершину) и две функции `connect` (соединить) с разным набором параметров,
причём одна из них является __закрытой__ (private).
Кроме этого, в классе имеется __операторная__ функция `get`, которая также является закрытой,
__свойство__ (val) `vertices` (вершины), которое опять-таки закрыто, 
и __вложенный__ класс `Vertex` (вершина) со свойствами `name` (имя) и `neighbors` (соседи).
Рассмотрим все эти элементы класса подробнее...
